name: Build MS-DOS 4

on:
  push:
    paths:
      - 'v4.0/**'
      - '.github/workflows/build.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dosemu2 and mtools
        run: |
          sudo add-apt-repository -y ppa:dosemu2/ppa
          sudo apt-get update
          sudo apt-get install -y dosemu2 mtools

      # Workaround for https://github.com/dosemu2/comcom64/pull/117
      # Remove once merged and released in dosemu2
      - name: Build patched comcom64
        run: |
          sudo add-apt-repository -y ppa:stsp-0/thunk-gen
          sudo apt-get update
          sudo apt-get install -y thunk-gen dj64-dev pkgconf nasm
          git clone --depth 1 --branch fix-expand-pluses-trailing-space \
            https://github.com/tgies/comcom64.git /tmp/comcom64
          cd /tmp/comcom64
          make
          sudo make install prefix=/usr

      - name: Build DOS 4
        run: |
          cd v4.0
          timeout 3600 ./mak.sh

      - name: Create hard disk image
        run: timeout 300 ./v4.0/mkhdimg.sh

      - name: Create boot floppy
        run: timeout 300 ./v4.0/mkhdimg.sh --floppy

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: dos4-binaries
          path: |
            v4.0/*.sys
            v4.0/*.com
            v4.0/*.exe
            v4.0/*.cpi
            v4.0/*.pro
            v4.0/*.dat
            v4.0/*.prt
            v4.0/*.hlp

      - name: Upload disk images
        uses: actions/upload-artifact@v4
        with:
          name: dos4-disk-images
          path: |
            v4.0/dos4.img
            v4.0/dos4.raw.img
            v4.0/dos4-boot.img
